services:
  _defaults:
    autowire: true
    autoconfigure: false
    public: false

  JWeiland\Infinitescrolling\EventListener\AddFrontendJavaScriptListener:
    public: true
    tags:
      - name: event.listener
        identifier: 'jweiland-infinitescrolling/add-frontend-javascript'
